# Generated by Django 5.1 on 2024-08-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
